### ISSUE TITLE
Authentication Failed - You do not have permissions to access the service

### ISSUE THREAD

**Issue by MetricCepheid** [ephun/YARGfm#1]
```
Traceback (most recent call last):
  File "C:\Users\<>\Documents\YARG\YARGfm-main\yargfm.py", line 32, in <module>
    network = pylast.LastFMNetwork(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<>\AppData\Local\Programs\Python\Python312\Lib\site-packages\pylast\__init__.py", line 660, in __init__
    super().__init__(
  File "C:\Users\<>\AppData\Local\Programs\Python\Python312\Lib\site-packages\pylast\__init__.py", line 210, in __init__
    self.session_key = sk_gen.get_session_key(self.username, self.password_hash)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<>\AppData\Local\Programs\Python\Python312\Lib\site-packages\pylast\__init__.py", line 1064, in get_session_key
    doc = request.execute()
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\<>\AppData\Local\Programs\Python\Python312\Lib\site-packages\pylast\__init__.py", line 939, in execute
    response = self._download_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<>\AppData\Local\Programs\Python\Python312\Lib\site-packages\pylast\__init__.py", line 928, in _download_response
    self._check_response_for_errors(response_text)
  File "C:\Users\<>\AppData\Local\Programs\Python\Python312\Lib\site-packages\pylast\__init__.py", line 957, in _check_response_for_errors
    raise WSError(self.network, status, details)
pylast.WSError: Authentication Failed - You do not have permissions to access the service
```

**Comment by ephun** [comment]
You've created your Last.fm API application and entered your key/secret?

**Comment by MetricCepheid** [comment]
So my issue was that I was typing my password wrong. lmao
